# Generated by Django 5.2.8 on 2026-02-02 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="docker_container_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="deployment",
            name="port",
            field=models.PositiveIntegerField(default=8000),
        ),
        migrations.AddField(
            model_name="deployment",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="modelversion",
            name="sample_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deployment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("DEPLOYING", "deploying"),
                    ("ACTIVE", "Active"),
                    ("STOPPED", "Stopped"),
                    ("FAILED", "Failed"),
                    ("DELETED", "deleted"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="owner",
            field=models.CharField(max_length=100),
        ),
    ]
