# Generated by Django 5.2.8 on 2026-02-02 16:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployment", "0003_alter_projet_owner"),
        ("users", "0001_initial"),  # Ensure users migration runs first
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='owner',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
