# Generated by Django 5.2.8 on 2026-02-02 12:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("deployment", "0002_deployment_docker_container_id_deployment_port_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseDrift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=600, null=True),
                ),
                ("features", models.JSONField(default=dict)),
                ("sample_count", models.IntegerField()),
                (
                    "model_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drifts",
                        to="deployment.modelversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataDrift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kl_divergence", models.FloatField()),
                ("wasserstein_distance", models.FloatField()),
                ("ks_statistic", models.FloatField()),
                ("chi_square", models.FloatField()),
                ("results", models.JSONField(default=dict)),
                ("scanned_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "model_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_drifts",
                        to="deployment.modelversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-scanned_at"],
            },
        ),
        migrations.CreateModel(
            name="DeploymentAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("high_cpu", "High CPU Usage"),
                            ("high_ram", "High RAM Usage"),
                            ("latency_spike", "Latency Spike"),
                            ("model_down", "Model is not responding"),
                            ("container_stopped", "Docker container stopped"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("resolved", models.BooleanField(default=False)),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="deployment.deployment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeploymentMonitoringRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpu_usage", models.FloatField()),
                ("ram_usage", models.FloatField()),
                ("latency_ms", models.FloatField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_records",
                        to="deployment.deployment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeploymentStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpu_usage", models.FloatField()),
                ("ram_usage", models.FloatField()),
                ("latency_ms", models.FloatField()),
                ("request_count", models.IntegerField()),
                ("error_count", models.IntegerField()),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "deployment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployment_stats",
                        to="deployment.deployment",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Samples",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.FileField(upload_to="samples/")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "model_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="deployment.modelversion",
                    ),
                ),
            ],
        ),
    ]
