# Generated by Django 5.2.8 on 2026-02-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datadrift",
            name="sample_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="deploymentmonitoringrecord",
            name="error_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="deploymentmonitoringrecord",
            name="request_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="deploymentalert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("high_cpu", "High CPU Usage"),
                    ("high_ram", "High RAM Usage"),
                    ("latency_spike", "Latency Spike"),
                    ("model_down", "Model is not responding"),
                    ("container_stopped", "Docker container stopped"),
                    ("errors_spike", "Errors Spike"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="samples",
            name="data",
            field=models.JSONField(),
        ),
    ]
